#CSV_PATH: "C:\Users\storm\PycharmProjects\myProjects\MadaReportss\MadaReports - MadaReports.csv"
encode:
  eight_bit: "utf-8"

json:
  key: "IDNum"
  space_between_rows: 4
  path:
    folder: "mada_reports_jsons"
    file: "mada_reports_jsons/mada_report1.json"

files:
  read: 'r'
  write: 'w'

rows:
  max: 50000