csv:
  path: "C:\\Users\\storm\\PycharmProjects\\myProjects\\MadaReportss\\MadaReports - MadaReports.csv"
encode:
  eight_bit: "utf-8"

json:
  key: "IDNum"
  space_between_rows: 4
  path:
    folder: "mada_reports_jsons"
    file: "mada_reports_jsons/mada_report"

files:
  read: 'r'
  write: 'w'
  next_file: 1
  first_file: 1

rows:
  max: 50000
  first: 0
  next_row: 1
  first_row: 0
